### ISSUE TITLE
error when compiling esphome code

### ISSUE THREAD

**Issue by harfordhawk** [ceaswaran/Smart-Contactless-Body-Temperature-Scanning-Station-ESP-Home-#1]
this is the error I get...

src/custom_mlx_sensor.h: In member function 'virtual void CustommlxSensor::update()':
src/custom_mlx_sensor.h:38:17: error: 'led' was not declared in this scope
    digitalWrite(led, HIGH); // Turn the LED on
                 ^
Compiling /data/contactless/.pioenvs/contactless/lib4d9/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o

can you tell me how to fix this?

**Comment by harfordhawk** [comment]
found error was the LED is not defined in the custom_mlx_sensor.h file. added #define led 13  near top to fix

**Comment by ceaswaran** [comment]
Yes I have removed the LED from this code & added Fast LED component in ESPhome Yaml.
I will update the code accordingly thanks

**Comment by harfordhawk** [comment]
I guess i still have this issue.. my led will not work with the code as it is. I think the reference to led has to be removed from the custom file, but I am not sure.

**Comment by ceaswaran** [comment]
ill check the code again today & give u feedback.

**Comment by ceaswaran** [comment]
> I guess i still have this issue.. my led will not work with the code as it is. I think the reference to led has to be removed from the custom file, but I am not sure.

custom_mlx_sensor.h code updated. can you compile with new code now & see confirm if it works.

**Comment by harfordhawk** [comment]
will close this as I think it is now an issue with my LED..
